parse_map = {
    "push": "C_PUSH",
    "pop": "C_POP",
    "add": "C_ARITHMETIC",
    "sub": "C_ARITHMETIC",
    "neg": "C_ARITHMETIC",
    "eq": "C_ARITHMETIC",
    "gt": "C_ARITHMETIC",
    "lt": "C_ARITHMETIC",
    "and": "C_ARITHMETIC",
    "or": "C_ARITHMETIC",
    "not": "C_ARITHMETIC",
    "label": "C_LABEL",
    "function": "C_FUNCTION",
    "goto": "C_GOTO",
    "if-goto": "C_IF",
    "return": "C_RETURN",
    "call": "C_CALL",
}